# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='U2U',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')])),
            ],
        ),
        migrations.AddField(
            model_name='u2u',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girls', to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='u2u',
            name='g',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boys', to='app01.UserInfo'),
        ),
    ]
