# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u2u',
            name='b',
        ),
        migrations.RemoveField(
            model_name='u2u',
            name='g',
        ),
        migrations.DeleteModel(
            name='U2U',
        ),
    ]
