# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170630_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='m',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
    ]
