# Generated by Django 2.0.3 on 2018-03-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180324_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='student_id',
        ),
    ]
