# Generated by Django 2.0.3 on 2018-03-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverifyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='send_type',
        ),
    ]
