# Generated by Django 2.0.3 on 2018-03-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_emailverifyrecord_send_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
