# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author2book',
            name='memo',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
