# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-25 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=108, verbose_name='权限'),
        ),
    ]
