# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bitrh',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
