# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180511_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=5),
        ),
    ]
