# Generated by Django 2.0.3 on 2018-03-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_info',
            new_name='Actor_info',
        ),
    ]
