# Generated by Django 2.0.3 on 2018-03-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0003_actor_info_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor_info',
            name='tel',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
