# Generated by Django 2.0.3 on 2018-03-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0004_actor_info_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor_info',
            name='tel',
            field=models.CharField(max_length=11),
        ),
    ]
