# Generated by Django 2.0.3 on 2018-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0006_actor_info_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor_info',
            name='college',
        ),
        migrations.RemoveField(
            model_name='actor_info',
            name='email',
        ),
        migrations.RemoveField(
            model_name='actor_info',
            name='name',
        ),
        migrations.RemoveField(
            model_name='actor_info',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='actor_info',
            name='tel',
        ),
        migrations.AddField(
            model_name='actor_info',
            name='college1',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='actor_info',
            name='college2',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='actor_info',
            name='email1',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='actor_info',
            name='email2',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='actor_info',
            name='member1',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='actor_info',
            name='member2',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='actor_info',
            name='student_id1',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AddField(
            model_name='actor_info',
            name='student_id2',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AddField(
            model_name='actor_info',
            name='team_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor_info',
            name='tel1',
            field=models.CharField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='actor_info',
            name='tel2',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
