# Generated by Django 2.0.3 on 2018-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0008_auto_20180321_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor_info',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
