# Generated by Django 2.0.3 on 2018-03-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0012_auto_20180321_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_info',
            name='key',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
