# Generated by Django 2.0.3 on 2018-03-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0015_auto_20180322_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_info',
            name='team_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
