# Generated by Django 2.0.3 on 2018-03-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0017_auto_20180322_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_info',
            name='team_key',
        ),
    ]
