# Generated by Django 2.0.3 on 2018-03-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0018_remove_team_info_team_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_info',
            name='team_key',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
