# Generated by Django 2.0.3 on 2018-03-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0019_team_info_team_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_info',
            name='team_key',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
