# Generated by Django 2.0.3 on 2018-03-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0024_auto_20180322_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor_info',
            name='actor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
