# Generated by Django 2.0.3 on 2018-03-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0025_actor_info_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor_info',
            name='actor',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='actor_info',
            name='team_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
