# Generated by Django 2.0.3 on 2018-03-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0026_auto_20180322_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor_info',
            old_name='actor',
            new_name='actor_name',
        ),
    ]
