# Generated by Django 2.0.3 on 2018-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0029_auto_20180323_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_info',
            name='college1',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='college2',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='email1',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='email2',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='leader_id',
            field=models.CharField(blank=True, default=None, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='member1',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='member2',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='student_id1',
            field=models.CharField(blank=True, default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='student_id2',
            field=models.CharField(blank=True, default=None, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='tel1',
            field=models.CharField(blank=True, default=None, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='tel2',
            field=models.CharField(blank=True, default=None, max_length=11),
        ),
    ]
