# Generated by Django 2.0.3 on 2018-03-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0030_auto_20180324_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor_info',
            old_name='actor_name',
            new_name='actor_id',
        ),
    ]
