# Generated by Django 2.0.3 on 2018-03-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0031_auto_20180325_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_info',
            name='member1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='member2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
