# Generated by Django 2.0.3 on 2018-03-27 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0035_auto_20180327_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.AlterModelOptions(
            name='actor_info',
            options={'verbose_name': '参与者状态', 'verbose_name_plural': '参与者状态'},
        ),
        migrations.AlterModelOptions(
            name='team_info',
            options={'verbose_name': '队伍信息', 'verbose_name_plural': '队伍信息'},
        ),
        migrations.AlterField(
            model_name='actor_info',
            name='actor_id',
            field=models.CharField(default=None, max_length=100, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='actor_info',
            name='is_added',
            field=models.BooleanField(default=False, verbose_name='是否已参加'),
        ),
        migrations.AlterField(
            model_name='actor_info',
            name='team_name',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='所参与队伍名'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='college1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='college2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='队伍创建时间'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='email1',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='email2',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='leader',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='队长'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='leader_college',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='leader_email',
            field=models.EmailField(blank=True, default=None, max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='leader_id',
            field=models.CharField(blank=True, default=None, max_length=9, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='leader_tel',
            field=models.CharField(blank=True, default=None, max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='member1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='队员一'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='member2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='队员二'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='student_id1',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='student_id2',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='team_key',
            field=models.CharField(default=None, max_length=10, unique=True, verbose_name='队伍密钥'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='team_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='队伍名'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='tel1',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='team_info',
            name='tel2',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
