# Generated by Django 2.0.3 on 2018-04-06 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0036_auto_20180327_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间'),
        ),
    ]
