# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-24 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='book', to='app01.Publisher'),
        ),
    ]
