# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-24 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kucun',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='sale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
