# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=64, verbose_name='项目名称')),
                ('kname', models.CharField(max_length=64, verbose_name='键值')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=32, verbose_name='任务名称')),
                ('svnversion', models.IntegerField(blank=True, null=True, verbose_name='渠道svn版本号')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('branch', models.CharField(max_length=128, verbose_name='分支名称')),
                ('release_info', models.CharField(max_length=512, verbose_name='发布信息')),
                ('build_cmd', models.CharField(blank=True, max_length=512, null=True, verbose_name='编译命令')),
                ('versionname', models.CharField(blank=True, max_length=16, null=True, verbose_name='versionname')),
                ('versioncode', models.CharField(blank=True, max_length=16, null=True, verbose_name='versioncode')),
                ('issue', models.CharField(blank=True, max_length=32, null=True, verbose_name='JIRA链接')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rim.Project', verbose_name='项目')),
            ],
        ),
    ]
