# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='issue',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='JIRA链接'),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='taskname',
            field=models.CharField(max_length=64, verbose_name='任务名称'),
        ),
    ]
