# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-26 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0002_auto_20200226_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['createtime'], 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别'),
        ),
    ]
