# Generated by Django 2.0.3 on 2020-03-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0003_auto_20200226_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=128, unique=True, verbose_name='组名')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['pid'], 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='releaseinfo',
            options={'ordering': ['-createtime'], 'verbose_name_plural': '发布信息'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='group',
            name='u2g',
            field=models.ManyToManyField(to='rim.User', verbose_name='关联组'),
        ),
    ]
