# Generated by Django 2.0.3 on 2020-03-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0004_auto_20200304_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='标题')),
                ('url', models.CharField(max_length=256, unique=True, verbose_name='含正则URL')),
                ('code', models.CharField(blank=True, default='list', max_length=32, null=True, verbose_name='代码')),
                ('menu_gp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rim.Permission', verbose_name='组内菜单')),
            ],
            options={
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name_plural': '用户组'},
        ),
        migrations.AlterField(
            model_name='group',
            name='u2g',
            field=models.ManyToManyField(blank=True, null=True, to='rim.User', verbose_name='关联用户'),
        ),
        migrations.AddField(
            model_name='permission',
            name='p2g',
            field=models.ManyToManyField(default=1, to='rim.Group', verbose_name='所属组'),
        ),
    ]
