# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-12 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0005_auto_20200309_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='code',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='menu_gp',
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='p2g',
            field=models.ManyToManyField(blank=True, null=True, to='rim.Group', verbose_name='所属组'),
        ),
    ]
