# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-18 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0006_auto_20200312_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': '用户组', 'verbose_name_plural': '用户组'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': '权限', 'verbose_name_plural': '权限表'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['pid'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='releaseinfo',
            options={'ordering': ['-createtime'], 'verbose_name': '发布信息', 'verbose_name_plural': '发布信息'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(default=1, max_length=128, unique=True, verbose_name='url名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=256, unique=True, verbose_name='含正则URL路径'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱*'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码*'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名*'),
        ),
    ]
