# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0007_auto_20200318_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.FileField(blank=True, null=True, upload_to='portrait', verbose_name='头像'),
        ),
    ]
