# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0008_user_portrait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portrait',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y%m%d/', verbose_name='头像'),
        ),
    ]
