# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='f',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ctime',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
