# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170629_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='ctime',
        ),
    ]
