# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_userinfo_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ctime',
            field=models.DateTimeField(null=True),
        ),
    ]
