# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_userinfo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='1111', max_length=254, null=True, unique=True),
        ),
    ]
