# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 04:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20170629_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.CharField(error_messages={'c1': '优先错信息1'}, max_length=32, null=True, validators=[django.core.validators.RegexValidator(code='c1', message='错误了', regex='root_\\d+')]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, default='1111', help_text='熬枯受淡发送到发送到', max_length=254, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
