# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='latest_date',
            field=models.DateField(blank=True, null=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='SN号'),
        ),
    ]
