# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20191208_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='capacity',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='容量'),
        ),
    ]
