# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20180514_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author2book',
            unique_together=set([('author', 'book')]),
        ),
    ]
