# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-17 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('bitrh', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
