# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-15 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '菜单一',
                'verbose_name_plural': '菜单一',
                'db_table': 'menu_one',
            },
        ),
        migrations.CreateModel(
            name='MenuThe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '菜单三',
                'verbose_name_plural': '菜单三',
                'db_table': 'menu_the',
            },
        ),
        migrations.CreateModel(
            name='MenuTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '菜单二',
                'verbose_name_plural': '菜单二',
                'db_table': 'menu_two',
            },
        ),
    ]
