# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 04:15
from __future__ import unicode_literals

import app01.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='new_name',
            field=app01.models.FixedCharField(default='张三', max_length=64),
        ),
    ]
