# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_person_new_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app01.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
