SEESION_ACTICE_TIME = 60
port = 20
user_num = 30

print(SEESION_ACTICE_TIME)
print(user_num)
print(60)
print(port)

print(SEESION_ACTICE_TIME)
print(SEESION_ACTICE_TIME)
print(SEESION_ACTICE_TIME)
print(SEESION_ACTICE_TIME)
print(SEESION_ACTICE_TIME)
print(SEESION_ACTICE_TIME)
print(SEESION_ACTICE_TIME)
print(SEESION_ACTICE_TIME)
print(SEESION_ACTICE_TIME)
