# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-17 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_id',
            new_name='pub',
        ),
    ]
