# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-05 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='/data/prod/', max_length=128, verbose_name='线上项目地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='servers',
            field=models.ManyToManyField(to='web.Server', verbose_name='关联服务器'),
        ),
    ]
