# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-17 08:53
from __future__ import unicode_literals

import app02.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20191117_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=app02.models.MyCharField(default='12301234123', max_length=11),
            preserve_default=False,
        ),
    ]
