# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-28 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_boy_girl_love'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='love',
            unique_together=set([('b', 'g')]),
        ),
    ]
