# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-28 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170628_1038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='love',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='love',
            name='b',
        ),
        migrations.RemoveField(
            model_name='love',
            name='g',
        ),
        migrations.DeleteModel(
            name='Love',
        ),
    ]
