# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-28 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_boy_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boy',
            name='m',
        ),
    ]
