# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-28 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_boy_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Boy')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Girl')),
            ],
        ),
        migrations.AddField(
            model_name='boy',
            name='m',
            field=models.ManyToManyField(through='app01.Love', to='app01.Girl'),
        ),
        migrations.AlterUniqueTogether(
            name='love',
            unique_together=set([('b', 'g')]),
        ),
    ]
